apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devenvironment_repo
  description: Sin descripción
  annotations:
    github.com/project-slug: crlsquilumba/devenvironment_repo
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
